console.log("Hello Winc Academy");
let name = "Geeske";
console.log(name);
let optellen = 2 + 3;
console.log(optellen);
let optellenString = "twee" + "drie";
console.log(optellenString);
let aftrekken = 5 - 3;
console.log(aftrekken);
let vermenigvuldigen = 4 * 2;
console.log(vermenigvuldigen);
let delen = 2134 / 1.34;
console.log(delen);
let procenten = 2345 % 50;
console.log(procenten);
let leeftijd = 30;
